/**
 * @jest-environment jsdom
 *
 * RED tests for resetImageAdjustForRecalibration (components/image.js).
 *
 * targetTask=adjust is the ONLY block type where the distance nudger (and
 * therefore the recalibrate button) is reachable MID-TRIAL
 * (threshold.js: pauseNudger is skipped for adjust). A recalibration mid-
 * adjust invalidates the in-progress adjustment: it was made at the old
 * viewing distance. The trial restarts in place — the pending adjustment
 * must be reset to the starting thresholdGuess so the participant redoes it
 * at the new distance (stimuli are separately regenerated by the
 * prestimulus rerun; the fresh stim re-binds via bindImageAdjustStim).
 *
 * These tests MUST fail until resetImageAdjustForRecalibration exists.
 */

import { jest } from "@jest/globals";

// ── Mocks for image.js's heavy import chain (mirrors
//    imageAndVideoGeneration.test.ts) ─────────────────────────────────────
jest.mock("../threshold", () => ({
  paramReader: { read: jest.fn(() => "") },
}));
jest.mock("../components/globalPsychoJS", () => ({
  psychoJS: { window: { _size: [800, 600] } },
}));
jest.mock("../components/global", () => ({
  correctAns: { current: undefined },
  imageConfig: {},
  imageFolders: {},
  imageQuestionAndAnswer: {},
  instructionFont: {},
  pastImages: [],
  rc: {},
  skipTrialOrBlock: {},
  status: {},
}));
// Imports an .mp3 asset jest can't parse.
jest.mock("../components/sound", () => ({
  getCorrectSynth: jest.fn(),
  getWrongSynth: jest.fn(),
}));

import {
  imageAdjustState,
  resetImageAdjustForRecalibration,
} from "../components/image.js";

const resetState = () => {
  imageAdjustState.active = false;
  imageAdjustState.finished = false;
  imageAdjustState.thresholdParameter = "";
  imageAdjustState.thresholdGuess = 0;
  imageAdjustState.thresholdGuessSide = 0;
  imageAdjustState.currentValue = 0;
  imageAdjustState.currentXYPx = null;
  imageAdjustState.zeroEccentricityXPx = null;
  imageAdjustState.pendingOffsetPx = 0;
  imageAdjustState.imageStim = null;
  imageAdjustState.keydownHandler = null;
};

describe("resetImageAdjustForRecalibration", () => {
  beforeEach(resetState);

  test("resets a pending eccentricity adjustment to the starting guess", () => {
    imageAdjustState.active = true;
    imageAdjustState.thresholdParameter = "targetEccentricityXDeg";
    imageAdjustState.thresholdGuess = 5;
    imageAdjustState.thresholdGuessSide = 1;
    imageAdjustState.currentValue = 12;
    imageAdjustState.currentXYPx = [300, 0];
    imageAdjustState.zeroEccentricityXPx = 100;
    imageAdjustState.pendingOffsetPx = 40;
    imageAdjustState.imageStim = { fake: "stim" };

    resetImageAdjustForRecalibration();

    expect(imageAdjustState.currentValue).toBe(5);
    // null forces re-initialization from thresholdGuess at the NEW viewing
    // distance on the next applyImageAdjustPosition (deg→px conversion).
    expect(imageAdjustState.currentXYPx).toBeNull();
    expect(imageAdjustState.zeroEccentricityXPx).toBeNull();
    expect(imageAdjustState.pendingOffsetPx).toBe(0);
    // Stale stim reference dropped; the rerun's fresh stim re-binds.
    expect(imageAdjustState.imageStim).toBeNull();
  });

  test("keeps the session alive (in-place trial restart, not cancellation)", () => {
    imageAdjustState.active = true;
    imageAdjustState.thresholdGuess = 5;
    const handler = () => {};
    imageAdjustState.keydownHandler = handler;

    resetImageAdjustForRecalibration();

    expect(imageAdjustState.active).toBe(true);
    expect(imageAdjustState.finished).toBe(false);
    // The same keydown listener stays registered — no duplicate handlers.
    expect(imageAdjustState.keydownHandler).toBe(handler);
  });

  test("revives an about-to-end trial (finished but response not yet recorded)", () => {
    imageAdjustState.active = true;
    imageAdjustState.finished = true;
    imageAdjustState.thresholdGuess = 5;
    imageAdjustState.currentValue = 9;

    resetImageAdjustForRecalibration();

    expect(imageAdjustState.finished).toBe(false);
    expect(imageAdjustState.currentValue).toBe(5);
  });

  test("no-op when no adjust session is active", () => {
    imageAdjustState.active = false;
    imageAdjustState.currentValue = 12;
    imageAdjustState.currentXYPx = [300, 0];

    resetImageAdjustForRecalibration();

    expect(imageAdjustState.currentValue).toBe(12);
    expect(imageAdjustState.currentXYPx).toEqual([300, 0]);
  });
});
