/*
  Do not modify this file! Run npm `npm run glossary` at ROOT of this project to fetch from the Google Sheets.
  https://docs.google.com/spreadsheets/d/1x65NjykMm-XUOz98Eu_oo6ON2xspm_h0Q0M2u6UGtug/edit#gid=1287694458 
*/

interface Glossary {
  [parameter: string]: { [field: string]: string | string[] };
}

export const GLOSSARY: Glossary = {
  _about: { name: "_about", availability: "now", type: "text", default: "" },
  _authorEmails: {
    name: "_authorEmails",
    availability: "now",
    type: "text",
    default: "",
  },
  _authors: {
    name: "_authors",
    availability: "now",
    type: "text",
    default: "",
  },
  _calibratePhoneMicBool: {
    name: "_calibratePhoneMicBool",
    availability: "now",
    type: "boolean",
    default: "FALSE",
  },
  _calibrateScreenSizeCookieBool: {
    name: "_calibrateScreenSizeCookieBool",
    availability: "now",
    type: "boolean",
    default: "FALSE",
  },
  _calibrateSoundAssumingThisICalibDBSPL: {
    name: "_calibrateSoundAssumingThisICalibDBSPL",
    availability: "now",
    type: "numerical",
    default: "76",
  },
  _calibrateTimingNumberAndSecs: {
    name: "_calibrateTimingNumberAndSecs",
    availability: "now",
    type: "text",
    default: "",
  },
  _compileAsNewExperimentBool: {
    name: "_compileAsNewExperimentBool",
    availability: "now",
    type: "boolean",
    default: "TRUE",
  },
  _consentForm: {
    name: "_consentForm",
    availability: "now",
    type: "text",
    default: "",
  },
  _daisyChainURLAfterEasyEyes: {
    name: "_daisyChainURLAfterEasyEyes",
    availability: "now",
    type: "text",
    default: "",
  },
  _daisyChainURLBeforeEasyEyes: {
    name: "_daisyChainURLBeforeEasyEyes",
    availability: "now",
    type: "text",
    default: "",
  },
  _dateCreated: {
    name: "_dateCreated",
    availability: "now",
    type: "date",
    default: " ",
  },
  _dateModified: {
    name: "_dateModified",
    availability: "now",
    type: "date",
    default: " ",
  },
  _debriefForm: {
    name: "_debriefForm",
    availability: "now",
    type: "text",
    default: "",
  },
  _debugBool: {
    name: "_debugBool",
    availability: "now",
    type: "boolean",
    default: "FALSE",
  },
  _experimentFilename: {
    name: "_experimentFilename",
    availability: "now",
    type: "text",
    default: "",
  },
  _experimentSavePartialResultsBool: {
    name: "_experimentSavePartialResultsBool",
    availability: "now",
    type: "boolean",
    default: "TRUE",
  },
  _invitePartingCommentsBool: {
    name: "_invitePartingCommentsBool",
    availability: "now",
    type: "boolean",
    default: "FALSE",
  },
  _language: {
    name: "_language",
    availability: "now",
    type: "categorical",
    default: "English",
    categories: [
      "English",
      "German",
      "French",
      "Spanish",
      "Portuguese",
      "Italian",
      "Romanian",
      "Polish",
      "Russian",
      "Armenian",
      "Finnish",
      "Georgian",
      "Hebrew",
      "Arabic",
      "Urdu",
      "Hindi",
      "Tamil",
      "Malayalam",
      "Telugu",
      "Kannada",
      "Bangla",
      "Indonesian",
      "Simplified Chinese",
      "Traditional Chinese",
      "Japanese",
      "Korean",
    ],
  },
  _languageSelectionByParticipantBool: {
    name: "_languageSelectionByParticipantBool",
    availability: "now",
    type: "boolean",
    default: "FALSE",
  },
  _needBrowser: {
    name: "_needBrowser",
    availability: "now",
    type: "multicategorical",
    default: "Chrome",
    categories: [
      "all",
      "Chrome",
      "Safari",
      "Firefox",
      "Opera",
      "Edge",
      "Chromium",
      "Tor",
      "Duckduckgo",
      "Brave",
      "Vivaldi",
      "Midori",
      "SamsungInternet",
      "UCBrowser",
      "Android",
      "Firefox",
      "QQBrowser",
      "Instabridge",
      "WhaleBrowser",
      "Puffin",
      "YandexBrowser",
      "EdgeLegacy",
      "Edge",
      "CocCoc",
      "notChrome",
      "notSafari",
      "notFirefox",
      "notOpera",
      "notEdge",
      "notChromium",
      "notTor",
      "notDuckduckgo",
      "notBrave",
      "notVivaldi",
      "notMidori",
      "notSamsungInternet",
      "notUCBrowser",
      "notAndroid",
      "notFirefox",
      "notQQBrowser",
      "notInstabridge",
      "notWhaleBrowser",
      "notPuffin",
      "notYandexBrowser",
      "notEdgeLegacy",
      "notEdge",
      "notCocCoc",
    ],
  },
  _needBrowserVersionMinimum: {
    name: "_needBrowserVersionMinimum",
    availability: "now",
    type: "integer",
    default: "0",
  },
  _needCameraBool: {
    name: "_needCameraBool",
    availability: "now",
    type: "boolean",
    default: "TRUE",
  },
  _needDeviceType: {
    name: "_needDeviceType",
    availability: "now",
    type: "multicategorical",
    default: "desktop",
    categories: ["all", "desktop", "tablet", "mobile"],
  },
  _needDisplay: {
    name: "_needDisplay",
    availability: "now",
    type: "multicategorical",
    default: "",
    categories: ["hdrMovie", "tenBit"],
  },
  _needSmartphoneTooBool: {
    name: "_needSmartphoneTooBool",
    availability: "now",
    type: "boolean",
    default: "FALSE",
  },
  _needOperatingSystem: {
    name: "_needOperatingSystem",
    availability: "now",
    type: "multicategorical",
    default: "all",
    categories: [
      "all",
      "macOS",
      "Windows",
      "ChromeOS",
      "ChromiumOS",
      "AndroidOS",
      "iOS",
      "SamsungOS",
      "KaiOS",
      "NokiaOS",
      "Series40OS",
      "Linux",
      "Ubuntu",
      "FreeBSD",
      "Debian",
      "Fedora",
      "Solaris",
      "CentOS",
      "Deepin",
      "notmacOS",
      "notWindows",
      "notChromeOS",
      "notChromiumOS",
      "notAndroidOS",
      "notiOS",
      "notSamsungOS",
      "notKaiOS",
      "notNokiaOS",
      "notSeries40OS",
      "notLinux",
      "notUbuntu",
      "notFreeBSD",
      "notDebian",
      "notFedora",
      "notSolaris",
      "notCentOS",
      "notDeepin",
    ],
  },
  _needProcessorCoresMinimum: {
    name: "_needProcessorCoresMinimum",
    availability: "now",
    type: "integer",
    default: "6",
  },
  _needScreenSizeMinimumPx: {
    name: "_needScreenSizeMinimumPx",
    availability: "now",
    type: "integer",
    default: "",
  },
  _needTimingToleranceSec: {
    name: "_needTimingToleranceSec",
    availability: "now",
    type: "numerical",
    default: "0.05",
  },
  _online1InternalName: {
    name: "_online1InternalName",
    availability: "now",
    type: "text",
    default: "",
  },
  _online1RecruitmentService: {
    name: "_online1RecruitmentService",
    availability: "now",
    type: "categorical",
    default: "none",
    categories: ["none", "Prolific"],
  },
  _online1Title: {
    name: "_online1Title",
    availability: "now",
    type: "text",
    default: "",
  },
  _online2Description: {
    name: "_online2Description",
    availability: "now",
    type: "text",
    default: "",
  },
  _online2Minutes: {
    name: "_online2Minutes",
    availability: "now",
    type: "numerical",
    default: "0",
  },
  _online2Participants: {
    name: "_online2Participants",
    availability: "now",
    type: "integer",
    default: "1",
  },
  _online2Pay: {
    name: "_online2Pay",
    availability: "now",
    type: "numerical",
    default: "0",
  },
  _online2PayCurrency: {
    name: "_online2PayCurrency",
    availability: "now",
    type: "categorical",
    default: "USD",
    categories: ["USD", "GBP"],
  },
  _online2PayPerHour: {
    name: "_online2PayPerHour",
    availability: "now",
    type: "numerical",
    default: "0",
  },
  _online2ProlificProjectID: {
    name: "_online2ProlificProjectID",
    availability: "now",
    type: "text",
    default: "",
  },
  _online2SaveIncompleteResponsesBool: {
    name: "_online2SaveIncompleteResponsesBool",
    availability: "now",
    type: "boolean",
    default: "TRUE",
  },
  _online2SubmissionApproval: {
    name: "_online2SubmissionApproval",
    availability: "now",
    type: "categorical",
    default: "manual",
    categories: ["manual", "automatic"],
  },
  _online3DeviceKind: {
    name: "_online3DeviceKind",
    availability: "now",
    type: "multicategorical",
    default: "Desktop",
    categories: ["mobile", "tablet", "desktop"],
  },
  _online3PhoneOperatingSystem: {
    name: "_online3PhoneOperatingSystem",
    availability: "now",
    type: "multicategorical",
    default: "",
    categories: ["Android", "iOS", "Windows", "Other", "Don't Know"],
  },
  _online3RequiredServices: {
    name: "_online3RequiredServices",
    availability: "now",
    type: "multicategorical",
    default: "",
    categories: ["audio", "camera", "microphone", "download"],
  },
  _online4AllowAfterHours: {
    name: "_online4AllowAfterHours",
    availability: "now",
    type: "numerical",
    default: "0",
  },
  _online4AllowCompletedExperiment: {
    name: "_online4AllowCompletedExperiment",
    availability: "now",
    type: "text",
    default: "",
  },
  _online4ApprovalRate: {
    name: "_online4ApprovalRate",
    availability: "now",
    type: "text",
    default: " 0,100",
  },
  _online4CustomAllowList: {
    name: "_online4CustomAllowList",
    availability: "now",
    type: "text",
    default: "",
  },
  _online4CustomBlockList: {
    name: "_online4CustomBlockList",
    availability: "now",
    type: "text",
    default: "",
  },
  _online4Location: {
    name: "_online4Location",
    availability: "now",
    type: "multicategorical",
    default: "All countries available",
    categories: [
      "All countries available",
      "USA",
      "UK",
      "Ireland",
      "Germany",
      "France",
      "Spain",
      "Afghanistan",
      "Aland Islands",
      "Albania",
      "Algeria",
      "American Samoa",
      "Andorra",
      "Angola",
      "Anguilla",
      "Antarctica",
      "Antigua and Barbuda",
      "Argentina",
      "Armenia",
      "Aruba",
      "Australia",
      "Austria",
      "Azerbaijan",
      "Bahamas",
      "Bahrain",
      "Bangladesh",
      "Barbados",
      "Belarus",
      "Belgium",
      "Belize",
      "Benin",
      "Bermuda",
      "Bhutan",
      "Bolivia",
      "Bonaire",
      "Bosnia and Herzegovina",
      "Botswana",
      "Bouvet Island",
      "Brazil",
      "British Indian Ocean Territory",
      "Brunei Darussalam",
      "Bulgaria",
      "Burkina Faso",
      "Burundi",
      "Cambodia",
      "Cameroon",
      "Canada",
      "Cape Verde",
      "Cayman Islands",
      "Central African Republic",
      "Chad",
      "Chile",
      "China",
      "Christmas Island",
      "Cocos (Keeling) Islands",
      "Colombia",
      "Comoros",
      "Congo",
      "Congo the Democratic Republic of the",
      "Cook Islands",
      "Costa Rica",
      "Cote d'Ivoire",
      "Croatia",
      "Cuba",
      "Curacao",
      "Cyprus",
      "Czech Republic",
      "Denmark",
      "Djibouti",
      "Dominica",
      "Dominican Republic",
      "Ecuador",
      "Egypt",
      "El Salvador",
      "Equatorial Guinea",
      "Eritrea",
      "Estonia",
      "Ethiopia",
      "Falkland Islands (Malvinas)",
      "Faroe Islands",
      "Fiji",
      "Finland",
      "French Guiana",
      "French Polynesia",
      "French Southern Territories",
      "Gabon",
      "Gambia",
      "Georgia",
      "Ghana",
      "Gibraltar",
      "Greece",
      "Greenland",
      "Grenada",
      "Guadeloupe",
      "Guam",
      "Guatemala",
      "Guernsey",
      "Guinea",
      "Guinea-Bissau",
      "Guyana",
      "Haiti",
      "Heard Island and McDonald Islands",
      "Holy See (Vatican City State)",
      "Honduras",
      "Hong Kong",
      "Hungary",
      "Iceland",
      "India",
      "Indonesia",
      "Iran",
      "Iraq",
      "Isle of Man",
      "Israel",
      "Italy",
      "Jamaica",
      "Japan",
      "Jersey",
      "Jordan",
      "Kazakhstan",
      "Kenya",
      "Kiribati",
      "Korea",
      "Kuwait",
      "Kyrgyzstan",
      "Lao People's Democratic Republic",
      "Latvia",
      "Lebanon",
      "Lesotho",
      "Liberia",
      "Libya",
      "Liechtenstein",
      "Lithuania",
      "Luxembourg",
      "Macao",
      "Macedonia",
      "Madagascar",
      "Malawi",
      "Malaysia",
      "Maldives",
      "Mali",
      "Malta",
      "Marshall Islands",
      "Martinique",
      "Mauritania",
      "Mauritius",
      "Mayotte",
      "Mexico",
      "Micronesia",
      "Moldova",
      "Monaco",
      "Mongolia",
      "Montenegro",
      "Montserrat",
      "Morocco",
      "Mozambique",
      "Myanmar",
      "Namibia",
      "Nauru",
      "Nepal",
      "Netherlands",
      "New Caledonia",
      "New Zealand",
      "Nicaragua",
      "Niger",
      "Nigeria",
      "Niue",
      "Norfolk Island",
      "Northern Mariana Islands",
      "Norway",
      "Oman",
      "Pakistan",
      "Palau",
      "Palestinian Territory",
      "Panama",
      "Papua New Guinea",
      "Paraguay",
      "Peru",
      "Philippines",
      "Pitcairn",
      "Poland",
      "Portugal",
      "Puerto Rico",
      "Qatar",
      "Reunion",
      "Romania",
      "Russian Federation",
      "Rwanda",
      "Saint Barthelemy",
      "Saint Helena",
      "Saint Kitts and Nevis",
      "Saint Lucia",
      "Saint Martin (French part)",
      "Saint Pierre and Miquelon",
      "Saint Vincent and the Grenadines",
      "Samoa",
      "San Marino",
      "Sao Tome and Principe",
      "Saudi Arabia",
      "Senegal",
      "Serbia",
      "Seychelles",
      "Sierra Leone",
      "Singapore",
      "Sint Maarten (Dutch part)",
      "Slovakia",
      "Slovenia",
      "Solomon Islands",
      "Somalia",
      "South Africa",
      "South Georgia and the South Sandwich Islands",
      "South Sudan",
      "Sri Lanka",
      "Sudan",
      "Suriname",
      "Svalbard and Jan Mayen",
      "Swaziland",
      "Sweden",
      "Switzerland",
      "Syrian Arab Republic",
      "Taiwan",
      "Tajikistan",
      "Tanzania",
      "Thailand",
      "Timor-Leste",
      "Togo",
      "Tokelau",
      "Tonga",
      "Trinidad and Tobago",
      "Tunisia",
      "Turkey",
      "Turkmenistan",
      "Turks and Caicos Islands",
      "Tuvalu",
      "Uganda",
      "Ukraine",
      "United Arab Emirates",
      "United States Minor Outlying Islands",
      "Uruguay",
      "Uzbekistan",
      "Vanuatu",
      "Venezuela",
      "Vietnam",
      "Wallis and Futuna",
      "Western Sahara",
      "Yemen",
      "Zambia",
      "Zimbabwe",
    ],
  },
  _online4ParticipantInPreviousStudyExclude: {
    name: "_online4ParticipantInPreviousStudyExclude",
    availability: "now",
    type: "text",
    default: "",
  },
  _online4ParticipantInPreviousStudyInclude: {
    name: "_online4ParticipantInPreviousStudyInclude",
    availability: "now",
    type: "text",
    default: "",
  },
  _online4Sample: {
    name: "_online4Sample",
    availability: "now",
    type: "categorical",
    default: "Standard",
    categories: ["UK", "USA", "Balanced", "Standard"],
  },
  _online5CochlearImplant: {
    name: "_online5CochlearImplant",
    availability: "now",
    type: "multicategorical",
    default: "",
    categories: ["Yes", "No", "Rather not say"],
  },
  _online5Dyslexia: {
    name: "_online5Dyslexia",
    availability: "now",
    type: "multicategorical",
    default: "",
    categories: ["diagnosed", "being diagnosed", "suspect", "no", "not saying"],
  },
  _online5HearingDifficulties: {
    name: "_online5HearingDifficulties",
    availability: "now",
    type: "multicategorical",
    default: "",
    categories: ["Yes", "No", "Rather not say"],
  },
  _online5LanguageFirst: {
    name: "_online5LanguageFirst",
    availability: "now",
    type: "multicategorical",
    default: "",
    categories: [
      "Afrikaans",
      "Albanian",
      "Amharic",
      "Arabic",
      "Armenian",
      "Basque",
      "Belarusian",
      "Bengali",
      "Bulgarian",
      "Burmese",
      "Cantonese",
      "Catalan",
      "Chinese",
      "Croatian",
      "Czech",
      "Danish",
      "Dari",
      "Dutch",
      "Dzongkha",
      "English",
      "Esperanto",
      "Estonian",
      "Faroese",
      "Farsi",
      "Finnish",
      "French",
      "Gaelic",
      "Galician",
      "Georgian",
      "German",
      "Greek",
      "Gujarati",
      "Hakka",
      "Hebrew",
      "Hindi",
      "Hungarian",
      "Icelandic",
      "Indonesian",
      "Inuktitut",
      "Italian",
      "Japanese",
      "Khmer",
      "Korean",
      "Kurdish",
      "Laotian",
      "Lappish",
      "Latvian",
      "Lithuanian",
      "Macedonian",
      "Malay",
      "Malayalam",
      "Maltese",
      "Mandarin",
      "Nepali",
      "Norwegian",
      "Papiamento",
      "Pashto",
      "Polish",
      "Portuguese",
      "Punjabi",
      "Romanian",
      "Russian",
      "Scots",
      "Serbian",
      "Slovak",
      "Slovenian",
      "Somali",
      "Spanish",
      "Swahili",
      "Swedish",
      "Tagalog-Filipino",
      "Tajik",
      "Tamil",
      "Telugu",
      "Thai",
      "Tibetan",
      "Tigrinya",
      "Tongan",
      "Turkish",
      "Turkmen",
      "Twi",
      "Ukrainian",
      "Urdu",
      "Uzbek",
      "Vietnamese",
      "Welsh",
      "Other",
    ],
  },
  _online5LanguageFluent: {
    name: "_online5LanguageFluent",
    availability: "now",
    type: "multicategorical",
    default: "",
    categories: [
      "Afrikaans",
      "Albanian",
      "Amharic",
      "Arabic",
      "Armenian",
      "Basque",
      "Belarusian",
      "Bengali",
      "Bulgarian",
      "Burmese",
      "Cantonese",
      "Catalan",
      "Chinese",
      "Croatian",
      "Czech",
      "Danish",
      "Dari",
      "Dutch",
      "Dzongkha",
      "English",
      "Esperanto",
      "Estonian",
      "Faroese",
      "Farsi",
      "Finnish",
      "French",
      "Gaelic",
      "Galician",
      "Georgian",
      "German",
      "Greek",
      "Gujarati",
      "Hakka",
      "Hebrew",
      "Hindi",
      "Hungarian",
      "Icelandic",
      "Indonesian",
      "Inuktitut",
      "Italian",
      "Japanese",
      "Khmer",
      "Korean",
      "Kurdish",
      "Laotian",
      "Lappish",
      "Latvian",
      "Lithuanian",
      "Macedonian",
      "Malay",
      "Malayalam",
      "Maltese",
      "Mandarin",
      "Nepali",
      "Norwegian",
      "Papiamento",
      "Pashto",
      "Polish",
      "Portuguese",
      "Punjabi",
      "Romanian",
      "Russian",
      "Scots",
      "Serbian",
      "Slovak",
      "Slovenian",
      "Somali",
      "Spanish",
      "Swahili",
      "Swedish",
      "Tagalog-Filipino",
      "Tajik",
      "Tamil",
      "Telugu",
      "Thai",
      "Tibetan",
      "Tigrinya",
      "Tongan",
      "Turkish",
      "Turkmen",
      "Twi",
      "Ukrainian",
      "Urdu",
      "Uzbek",
      "Vietnamese",
      "Welsh",
      "Other",
    ],
  },
  _online5LanguagePrimary: {
    name: "_online5LanguagePrimary",
    availability: "now",
    type: "multicategorical",
    default: "",
    categories: [
      "Afrikaans",
      "Albanian",
      "Amharic",
      "Arabic",
      "Armenian",
      "Basque",
      "Belarusian",
      "Bengali",
      "Bulgarian",
      "Burmese",
      "Cantonese",
      "Catalan",
      "Chinese",
      "Croatian",
      "Czech",
      "Danish",
      "Dari",
      "Dutch",
      "Dzongkha",
      "English",
      "Esperanto",
      "Estonian",
      "Faroese",
      "Farsi",
      "Finnish",
      "French",
      "Gaelic",
      "Galician",
      "Georgian",
      "German",
      "Greek",
      "Gujarati",
      "Hakka",
      "Hebrew",
      "Hindi",
      "Hungarian",
      "Icelandic",
      "Indonesian",
      "Inuktitut",
      "Italian",
      "Japanese",
      "Khmer",
      "Korean",
      "Kurdish",
      "Laotian",
      "Lappish",
      "Latvian",
      "Lithuanian",
      "Macedonian",
      "Malay",
      "Malayalam",
      "Maltese",
      "Mandarin",
      "Nepali",
      "Norwegian",
      "Papiamento",
      "Pashto",
      "Polish",
      "Portuguese",
      "Punjabi",
      "Romanian",
      "Russian",
      "Scots",
      "Serbian",
      "Slovak",
      "Slovenian",
      "Somali",
      "Spanish",
      "Swahili",
      "Swedish",
      "Tagalog-Filipino",
      "Tajik",
      "Tamil",
      "Telugu",
      "Thai",
      "Tibetan",
      "Tigrinya",
      "Tongan",
      "Turkish",
      "Turkmen",
      "Twi",
      "Ukrainian",
      "Urdu",
      "Uzbek",
      "Vietnamese",
      "Welsh",
      "Other",
    ],
  },
  _online5LanguageRelatedDisorders: {
    name: "_online5LanguageRelatedDisorders",
    availability: "now",
    type: "multicategorical",
    default: "",
    categories: [
      "reading difficulty",
      "writing difficulty",
      "other language related disorder",
      "none",
      "not applicable",
    ],
  },
  _online5MusicalInstrumentExperience: {
    name: "_online5MusicalInstrumentExperience",
    availability: "now",
    type: "multicategorical",
    default: "",
    categories: ["No", "0-1", "1-2", "2-3", "3-4", "5+"],
  },
  _online5Vision: {
    name: "_online5Vision",
    availability: "now",
    type: "multicategorical",
    default: "",
    categories: ["Yes", "No", "Rather not say"],
  },
  _online5VisionCorrection: {
    name: "_online5VisionCorrection",
    availability: "now",
    type: "multicategorical",
    default: "",
    categories: ["glasses", "contacts", "both", "neither"],
  },
  _online5VRExperiences: {
    name: "_online5VRExperiences",
    availability: "now",
    type: "multicategorical",
    default: "",
    categories: [
      "Virtual reality",
      "Augmented reality",
      "Mixed reality",
      "Other",
      "Not applicable",
    ],
  },
  _online5VRHeadset: {
    name: "_online5VRHeadset",
    availability: "now",
    type: "multicategorical",
    default: "",
    categories: ["Yes", "No", "Don't know", "Not applicable"],
  },
  _online5VRHeadsetUsage: {
    name: "_online5VRHeadsetUsage",
    availability: "now",
    type: "multicategorical",
    default: "",
    categories: ["0", "1-5", "6-10", "11-15", "more than 15", "Not applicable"],
  },
  _participantIDGetBool: {
    name: "_participantIDGetBool",
    availability: "now",
    type: "boolean",
    default: "FALSE",
  },
  _participantIDPutBool: {
    name: "_participantIDPutBool",
    availability: "now",
    type: "boolean",
    default: "FALSE",
  },
  _pavloviaPreferRunningModeBool: {
    name: "_pavloviaPreferRunningModeBool",
    availability: "now",
    type: "boolean",
    default: "TRUE",
  },
  _saveEachBlockBool: {
    name: "_saveEachBlockBool",
    availability: "now",
    type: "boolean",
    default: "FALSE",
  },
  _trackGazeExternallyBool: {
    name: "_trackGazeExternallyBool",
    availability: "now",
    type: "boolean",
    default: "FALSE",
  },
  "%": { name: "%", availability: "now", type: "", default: "" },
  block: { name: "block", availability: "now", type: "integer", default: "1" },
  blockShuffleGroups1: {
    name: "blockShuffleGroups1",
    availability: "now",
    type: "text",
    default: "",
  },
  blockShuffleGroups2: {
    name: "blockShuffleGroups2",
    availability: "now",
    type: "text",
    default: "",
  },
  blockShuffleGroups3: {
    name: "blockShuffleGroups3",
    availability: "now",
    type: "text",
    default: "",
  },
  blockShuffleGroups4: {
    name: "blockShuffleGroups4",
    availability: "now",
    type: "text",
    default: "",
  },
  calibrateBlindSpotBool: {
    name: "calibrateBlindSpotBool",
    availability: "now",
    type: "boolean",
    default: "FALSE",
  },
  calibrateDistanceCheckBool: {
    name: "calibrateDistanceCheckBool",
    availability: "now",
    type: "boolean",
    default: "FALSE",
  },
  calibrateFrameRateUnderStressBool: {
    name: "calibrateFrameRateUnderStressBool",
    availability: "now",
    type: "boolean",
    default: "FALSE",
  },
  calibrateGazeCheckBool: {
    name: "calibrateGazeCheckBool",
    availability: "now",
    type: "boolean",
    default: "FALSE",
  },
  calibratePupillaryDistanceBool: {
    name: "calibratePupillaryDistanceBool",
    availability: "now",
    type: "boolean",
    default: "FALSE",
  },
  calibrateScreenSizeBool: {
    name: "calibrateScreenSizeBool",
    availability: "now",
    type: "boolean",
    default: "TRUE",
  },
  calibrateScreenSizeCheckBool: {
    name: "calibrateScreenSizeCheckBool",
    availability: "now",
    type: "boolean",
    default: "FALSE",
  },
  calibrateSound1000HzBool: {
    name: "calibrateSound1000HzBool",
    availability: "now",
    type: "boolean",
    default: "FALSE",
  },
  calibrateSound1000HzDB: {
    name: "calibrateSound1000HzDB",
    availability: "now",
    type: "text",
    default: "-60, -50, -40, -30, -20, -15, -10, -3.1",
  },
  calibrateSoundAllHzBool: {
    name: "calibrateSoundAllHzBool",
    availability: "now",
    type: "boolean",
    default: "FALSE",
  },
  calibrateSoundAllHzDB: {
    name: "calibrateSoundAllHzDB",
    availability: "now",
    type: "text",
    default: "-13.1",
  },
  calibrateSoundMaxHz: {
    name: "calibrateSoundMaxHz",
    availability: "now",
    type: "numerical",
    default: "10000",
  },
  calibrateSoundMinHz: {
    name: "calibrateSoundMinHz",
    availability: "now",
    type: "numerical",
    default: "40",
  },
  calibrateSoundSaveToCSVBool: {
    name: "calibrateSoundSaveToCSVBool",
    availability: "now",
    type: "boolean",
    default: "FALSE",
  },
  calibrateSoundToleranceDB: {
    name: "calibrateSoundToleranceDB",
    availability: "now",
    type: "numerical",
    default: "3",
  },
  calibrateTrackDistanceBool: {
    name: "calibrateTrackDistanceBool",
    availability: "now",
    type: "boolean",
    default: "FALSE",
  },
  calibrateTrackDistanceCheckCm: {
    name: "calibrateTrackDistanceCheckCm",
    availability: "now",
    type: "text",
    default: "25, 35, 50, 70, 100, 140, 160, 180",
  },
  calibrateTrackDistanceCheckBool: {
    name: "calibrateTrackDistanceCheckBool",
    availability: "now",
    type: "boolean",
    default: "FALSE",
  },
  calibrateTrackGazeBool: {
    name: "calibrateTrackGazeBool",
    availability: "now",
    type: "boolean",
    default: "FALSE",
  },
  conditionEnabledBool: {
    name: "conditionEnabledBool",
    availability: "now",
    type: "boolean",
    default: "TRUE",
  },
  conditionGroup: {
    name: "conditionGroup",
    availability: "now",
    type: "integer",
    default: "0",
  },
  conditionName: {
    name: "conditionName",
    availability: "now",
    type: "text",
    default: "",
  },
  conditionTrials: {
    name: "conditionTrials",
    availability: "now",
    type: "integer",
    default: "35",
  },
  errorBool: {
    name: "errorBool",
    availability: "now",
    type: "boolean",
    default: "FALSE",
  },
  errorEndsExperimentBool: {
    name: "errorEndsExperimentBool",
    availability: "now",
    type: "",
    default: "",
  },
  fixationCheckBool: {
    name: "fixationCheckBool",
    availability: "now",
    type: "boolean",
    default: "TRUE",
  },
  fixationLocationStrategy: {
    name: "fixationLocationStrategy",
    availability: "now",
    type: "categorical",
    default: "centerFixation",
    categories: [
      "centerFixation",
      "centerFixationAndTargets",
      "centerTargets",
      "asSpecified",
    ],
  },
  fixationLocationXScreen: {
    name: "fixationLocationXScreen",
    availability: "now",
    type: "numerical",
    default: "0.5",
  },
  fixationLocationYScreen: {
    name: "fixationLocationYScreen",
    availability: "now",
    type: "numerical",
    default: "0.5",
  },
  fixationRequestedOffscreenBool: {
    name: "fixationRequestedOffscreenBool",
    availability: "now",
    type: "boolean",
    default: "FALSE",
  },
  flankerCharacterSet: {
    name: "flankerCharacterSet",
    availability: "now",
    type: "text",
    default: "abcdefghijklmnopqrstuvwxyz",
  },
  flankerFont: {
    name: "flankerFont",
    availability: "now",
    type: "text",
    default: "Roboto Mono",
  },
  flankerFontSource: {
    name: "flankerFontSource",
    availability: "now",
    type: "categorical",
    default: "google",
    categories: ["file", "google", "browser"],
  },
  flankerNumber: {
    name: "flankerNumber",
    availability: "now",
    type: "integer",
    default: "1",
  },
  flankerSpacingDeg: {
    name: "flankerSpacingDeg",
    availability: "now",
    type: "numerical",
    default: "",
  },
  flipScreenHorizontallyBool: {
    name: "flipScreenHorizontallyBool",
    availability: "now",
    type: "boolean",
    default: "FALSE",
  },
  font: {
    name: "font",
    availability: "now",
    type: "text",
    default: "Roboto Mono",
  },
  fontCharacterSet: {
    name: "fontCharacterSet",
    availability: "now",
    type: "text",
    default: "abcdefghijklmnopqrstuvwxyz",
  },
  fontColorRGBA: {
    name: "fontColorRGBA",
    availability: "now",
    type: "text",
    default: "0,0,0,1",
  },
  fontFeatureSettings: {
    name: "fontFeatureSettings",
    availability: "now",
    type: "text",
    default: "",
  },
  fontKerning: {
    name: "fontKerning",
    availability: "now",
    type: "text",
    default: "normal",
  },
  fontLeftToRightBool: {
    name: "fontLeftToRightBool",
    availability: "now",
    type: "boolean",
    default: "TRUE",
  },
  fontMaxPx: {
    name: "fontMaxPx",
    availability: "now",
    type: "numerical",
    default: "600",
  },
  fontPadding: {
    name: "fontPadding",
    availability: "now",
    type: "numerical",
    default: "0.5",
  },
  fontSource: {
    name: "fontSource",
    availability: "now",
    type: "categorical",
    default: "google",
    categories: ["file", "google", "browser"],
  },
  fontStyle: {
    name: "fontStyle",
    availability: "now",
    type: "categorical",
    default: "regular",
    categories: ["regular", "bold", "italic", "boldItalic"],
  },
  fontTrackingForLetters: {
    name: "fontTrackingForLetters",
    availability: "now",
    type: "numerical",
    default: "0",
  },
  fontTrackingForWords: {
    name: "fontTrackingForWords",
    availability: "now",
    type: "numerical",
    default: "0",
  },
  fontVariableSettings: {
    name: "fontVariableSettings",
    availability: "now",
    type: "text",
    default: "",
  },
  fontWeight: {
    name: "fontWeight",
    availability: "now",
    type: "numerical",
    default: "",
  },
  instructionFont: {
    name: "instructionFont",
    availability: "now",
    type: "text",
    default: "Verdana",
  },
  instructionFontLeftToRightBool: {
    name: "instructionFontLeftToRightBool",
    availability: "now",
    type: "boolean",
    default: "TRUE",
  },
  instructionFontSource: {
    name: "instructionFontSource",
    availability: "now",
    type: "categorical",
    default: "browser",
    categories: ["file", "google", "browser"],
  },
  instructionForBlock: {
    name: "instructionForBlock",
    availability: "now",
    type: "text",
    default: "",
  },
  instructionForExperiment: {
    name: "instructionForExperiment",
    availability: "now",
    type: "text",
    default: "",
  },
  instructionForResponse: {
    name: "instructionForResponse",
    availability: "now",
    type: "text",
    default: "",
  },
  internationalPhrasesURL: {
    name: "internationalPhrasesURL",
    availability: "now",
    type: "text",
    default: "",
  },
  instructionForResponseWhere: {
    name: "instructionForResponseWhere",
    availability: "now",
    type: "categorical",
    default: "topLeft",
    categories: ["none", "topLeft", "bottomLeft"],
  },
  instructionForStimulus: {
    name: "instructionForStimulus",
    availability: "now",
    type: "text",
    default: "",
  },
  instructionForStimulusLocation: {
    name: "instructionForStimulusLocation",
    availability: "now",
    type: "categorical",
    default: "upperLeft",
    categories: ["top", "upperLeft", "upperRight"],
  },
  instructionLanguage: {
    name: "instructionLanguage",
    availability: "now",
    type: "categorical",
    default: "English",
    categories: [""],
  },
  internationalTableURL: {
    name: "internationalTableURL",
    availability: "now",
    type: "text",
    default: "",
  },
  invitePartingCommentsBool: {
    name: "invitePartingCommentsBool",
    availability: "now",
    type: "boolean",
    default: "FALSE",
  },
  logQuestBool: {
    name: "logQuestBool",
    availability: "now",
    type: "boolean",
    default: "FALSE",
  },
  markingBlankedNearTargetBool: {
    name: "markingBlankedNearTargetBool",
    availability: "now",
    type: "boolean",
    default: "FALSE",
  },
  markingBlankingRadiusReEccentricity: {
    name: "markingBlankingRadiusReEccentricity",
    availability: "now",
    type: "numerical",
    default: "0.5",
  },
  markingBlankingRadiusReTargetHeight: {
    name: "markingBlankingRadiusReTargetHeight",
    availability: "now",
    type: "numerical",
    default: "1",
  },
  markingClippedToStimulusRectBool: {
    name: "markingClippedToStimulusRectBool",
    availability: "now",
    type: "boolean",
    default: "FALSE",
  },
  markingFixationHotSpotRadiusDeg: {
    name: "markingFixationHotSpotRadiusDeg",
    availability: "now",
    type: "numerical",
    default: "0.1",
  },
  markingFixationMotionPeriodSec: {
    name: "markingFixationMotionPeriodSec",
    availability: "now",
    type: "numerical",
    default: "10",
  },
  markingFixationMotionRadiusDeg: {
    name: "markingFixationMotionRadiusDeg",
    availability: "now",
    type: "numerical",
    default: "0.5",
  },
  markingFixationStrokeLengthDeg: {
    name: "markingFixationStrokeLengthDeg",
    availability: "now",
    type: "numerical",
    default: "2",
  },
  markingFixationStrokeThickening: {
    name: "markingFixationStrokeThickening",
    availability: "now",
    type: "numerical",
    default: "1.4",
  },
  markingFixationStrokeThicknessDeg: {
    name: "markingFixationStrokeThicknessDeg",
    availability: "now",
    type: "numerical",
    default: "0.05",
  },
  markingOffsetBeforeTargetOnsetSecs: {
    name: "markingOffsetBeforeTargetOnsetSecs",
    availability: "now",
    type: "numerical",
    default: "0",
  },
  markingOnsetAfterTargetOffsetSecs: {
    name: "markingOnsetAfterTargetOffsetSecs",
    availability: "now",
    type: "numerical",
    default: "0",
  },
  markingTargetStrokeLengthDeg: {
    name: "markingTargetStrokeLengthDeg",
    availability: "now",
    type: "numerical",
    default: "1",
  },
  markingTargetStrokeThicknessDeg: {
    name: "markingTargetStrokeThicknessDeg",
    availability: "now",
    type: "numerical",
    default: "0.03",
  },
  markTheFixationBool: {
    name: "markTheFixationBool",
    availability: "now",
    type: "boolean",
    default: "TRUE",
  },
  markThePossibleTargetsBool: {
    name: "markThePossibleTargetsBool",
    availability: "now",
    type: "boolean",
    default: "FALSE",
  },
  maskerBaseFrequencyMultiplier: {
    name: "maskerBaseFrequencyMultiplier",
    availability: "now",
    type: "numerical",
    default: "2",
  },
  maskerSoundDBSPL: {
    name: "maskerSoundDBSPL",
    availability: "now",
    type: "numerical",
    default: "-100",
  },
  maskerSoundFolder: {
    name: "maskerSoundFolder",
    availability: "now",
    type: "text",
    default: "",
  },
  maskerSoundPhrase: {
    name: "maskerSoundPhrase",
    availability: "now",
    type: "text",
    default: "",
  },
  movieComputeJS: {
    name: "movieComputeJS",
    availability: "now",
    type: "text",
    default: "",
  },
  movieHz: {
    name: "movieHz",
    availability: "now",
    type: "numerical",
    default: "60",
  },
  movieLuminanceNit: {
    name: "movieLuminanceNit",
    availability: "now",
    type: "numerical",
    default: "-1",
  },
  moviePQEncodedBool: {
    name: "moviePQEncodedBool",
    availability: "now",
    type: "boolean",
    default: "FALSE",
  },
  movieRectDeg: {
    name: "movieRectDeg",
    availability: "now",
    type: "text",
    default: "",
  },
  movieRectPxContainsRectDegBool: {
    name: "movieRectPxContainsRectDegBool",
    availability: "now",
    type: "boolean",
    default: "FALSE",
  },
  movieSec: {
    name: "movieSec",
    availability: "now",
    type: "numerical",
    default: "60",
  },
  movieTargetDelaySec: {
    name: "movieTargetDelaySec",
    availability: "now",
    type: "numerical",
    default: "0",
  },
  needScreenHeightUpToDeg: {
    name: "needScreenHeightUpToDeg",
    availability: "now",
    type: "numerical",
    default: "",
  },
  needScreenWidthUpToDeg: {
    name: "needScreenWidthUpToDeg",
    availability: "now",
    type: "numerical",
    default: "",
  },
  needTargetSizeDownToDeg: {
    name: "needTargetSizeDownToDeg",
    availability: "now",
    type: "numerical",
    default: "0",
  },
  notes: { name: "notes", availability: "now", type: "text", default: "" },
  "questionAndAnswer@@": {
    name: "questionAndAnswer@@",
    availability: "now",
    type: "text",
    default: "",
  },
  readingCorpusShuffleBool: {
    name: "readingCorpusShuffleBool",
    availability: "now",
    type: "boolean",
    default: "FALSE",
  },
  readingCorpus: {
    name: "readingCorpus",
    availability: "now",
    type: "text",
    default: "",
  },
  readingCorpusEndlessBool: {
    name: "readingCorpusEndlessBool",
    availability: "now",
    type: "boolean",
    default: "",
  },
  readingDefineSingleLineSpacingAs: {
    name: "readingDefineSingleLineSpacingAs",
    availability: "now",
    type: "categorical",
    default: "nominalSize",
    categories: ["nominalSize", "explicit"],
  },
  readingFirstFewWords: {
    name: "readingFirstFewWords",
    availability: "now",
    type: "text",
    default: "",
  },
  readingLinesPerPage: {
    name: "readingLinesPerPage",
    availability: "now",
    type: "numerical",
    default: "4",
  },
  readingMaxCharactersPerLine: {
    name: "readingMaxCharactersPerLine",
    availability: "now",
    type: "numerical",
    default: "57",
  },
  readingMultipleOfSingleLineSpacing: {
    name: "readingMultipleOfSingleLineSpacing",
    availability: "now",
    type: "numerical",
    default: "1.2",
  },
  readingNominalSizeDeg: {
    name: "readingNominalSizeDeg",
    availability: "now",
    type: "numerical",
    default: "1",
  },
  readingNumberOfPossibleAnswers: {
    name: "readingNumberOfPossibleAnswers",
    availability: "now",
    type: "integer",
    default: "4",
  },
  readingNumberOfQuestions: {
    name: "readingNumberOfQuestions",
    availability: "now",
    type: "integer",
    default: "3",
  },
  readingPages: {
    name: "readingPages",
    availability: "now",
    type: "numerical",
    default: "4",
  },
  readingSetSizeBy: {
    name: "readingSetSizeBy",
    availability: "now",
    type: "categorical",
    default: "spacing",
    categories: ["nominal", "xHeight", "spacing"],
  },
  readingSingleLineSpacingDeg: {
    name: "readingSingleLineSpacingDeg",
    availability: "now",
    type: "numerical",
    default: "1",
  },
  readingSpacingDeg: {
    name: "readingSpacingDeg",
    availability: "now",
    type: "numerical",
    default: "0.5",
  },
  readingTargetMaxWordFrequency: {
    name: "readingTargetMaxWordFrequency",
    availability: "now",
    type: "numerical",
    default: "4.30E-04",
  },
  readingXHeightDeg: {
    name: "readingXHeightDeg",
    availability: "now",
    type: "numerical",
    default: "1",
  },
  responseAllowedEarlyBool: {
    name: "responseAllowedEarlyBool",
    availability: "now",
    type: "boolean",
    default: "TRUE",
  },
  responseCharacterHasMedialShapeBool: {
    name: "responseCharacterHasMedialShapeBool",
    availability: "now",
    type: "boolean",
    default: "FALSE",
  },
  responseClickedBool: {
    name: "responseClickedBool",
    availability: "now",
    type: "boolean",
    default: "TRUE",
  },
  responseEscapeOptionsBool: {
    name: "responseEscapeOptionsBool",
    availability: "now",
    type: "boolean",
    default: "FALSE",
  },
  responseMustClickCrosshairBool: {
    name: "responseMustClickCrosshairBool",
    availability: "now",
    type: "boolean",
    default: "TRUE",
  },
  responseMustTrackCrosshairBool: {
    name: "responseMustTrackCrosshairBool",
    availability: "now",
    type: "boolean",
    default: "TRUE",
  },
  responseMustTrackContinuouslyBool: {
    name: "responseMustTrackContinuouslyBool",
    availability: "now",
    type: "boolean",
    default: "TRUE",
  },
  responseMustTrackMaxSec: {
    name: "responseMustTrackMaxSec",
    availability: "now",
    type: "numerical",
    default: "1.25",
  },
  responseMustTrackMinSec: {
    name: "responseMustTrackMinSec",
    availability: "now",
    type: "numerical",
    default: "0.75",
  },
  responseNegativeFeedbackBool: {
    name: "responseNegativeFeedbackBool",
    availability: "now",
    type: "boolean",
    default: "FALSE",
  },
  responsePositiveFeedbackBool: {
    name: "responsePositiveFeedbackBool",
    availability: "now",
    type: "boolean",
    default: "TRUE",
  },
  responsePurrWhenReadyBool: {
    name: "responsePurrWhenReadyBool",
    availability: "now",
    type: "boolean",
    default: "TRUE",
  },
  responseSpokenBool: {
    name: "responseSpokenBool",
    availability: "now",
    type: "boolean",
    default: "FALSE",
  },
  responseTypedBool: {
    name: "responseTypedBool",
    availability: "now",
    type: "boolean",
    default: "TRUE",
  },
  responseTypedEasyEyesKeypadBool: {
    name: "responseTypedEasyEyesKeypadBool",
    availability: "now",
    type: "boolean",
    default: "FALSE",
  },
  needEasyEyesKeypadBeyondCm: {
    name: "needEasyEyesKeypadBeyondCm",
    availability: "now",
    type: "boolean",
    default: "FALSE",
  },
  rsvpReadingFlankerCharacterSet: {
    name: "rsvpReadingFlankerCharacterSet",
    availability: "now",
    type: "text",
    default: "",
  },
  rsvpReadingFlankTargetWithLettersBool: {
    name: "rsvpReadingFlankTargetWithLettersBool",
    availability: "now",
    type: "boolean",
    default: "FALSE",
  },
  rsvpReadingNumberOfResponseOptions: {
    name: "rsvpReadingNumberOfResponseOptions",
    availability: "now",
    type: "numerical",
    default: "6",
  },
  rsvpReadingNumberOfWords: {
    name: "rsvpReadingNumberOfWords",
    availability: "now",
    type: "numerical",
    default: "6",
  },
  rsvpReadingRequireUniqueWordsBool: {
    name: "rsvpReadingRequireUniqueWordsBool",
    availability: "now",
    type: "boolean",
    default: "TRUE",
  },
  screenColorRGB: {
    name: "screenColorRGB",
    availability: "now",
    type: "text",
    default: "0.92,0.92,0.92",
  },
  screenshotBool: {
    name: "screenshotBool",
    availability: "now",
    type: "boolean",
    default: "FALSE",
  },
  setResolutionPxPerCm: {
    name: "setResolutionPxPerCm",
    availability: "now",
    type: "numerical",
    default: "",
  },
  setResolutionPxPerDeg: {
    name: "setResolutionPxPerDeg",
    availability: "now",
    type: "numerical",
    default: "",
  },
  showBeepButtonOnBlockInstructionBool: {
    name: "showBeepButtonOnBlockInstructionBool",
    availability: "now",
    type: "boolean",
    default: "TRUE",
  },
  showBoundingBoxBool: {
    name: "showBoundingBoxBool",
    availability: "now",
    type: "boolean",
    default: "FALSE",
  },
  showCharacterSetBoundingBoxBool: {
    name: "showCharacterSetBoundingBoxBool",
    availability: "now",
    type: "boolean",
    default: "FALSE",
  },
  showCharacterSetForAllResponsesBool: {
    name: "showCharacterSetForAllResponsesBool",
    availability: "now",
    type: "boolean",
    default: "FALSE",
  },
  showCharacterSetWhere: {
    name: "showCharacterSetWhere",
    availability: "now",
    type: "categorical",
    default: "bottom",
    categories: ["none", "bottom", "top", "left", "right"],
  },
  showCharacterSetWithLabelsBool: {
    name: "showCharacterSetWithLabelsBool",
    availability: "now",
    type: "boolean",
    default: "FALSE",
  },
  showConditionNameBool: {
    name: "showConditionNameBool",
    availability: "now",
    type: "boolean",
    default: "FALSE",
  },
  showCounterBool: {
    name: "showCounterBool",
    availability: "now",
    type: "boolean",
    default: "TRUE",
  },
  showCounterWhere: {
    name: "showCounterWhere",
    availability: "now",
    type: "categorical",
    default: "bottomRight",
    categories: ["bottomLeft", "bottomRight", "bottomCenter"],
  },
  showExperimentNameBool: {
    name: "showExperimentNameBool",
    availability: "now",
    type: "boolean",
    default: "FALSE",
  },
  showFixationMarkBool: {
    name: "showFixationMarkBool",
    availability: "now",
    type: "boolean",
    default: "TRUE",
  },
  showFPSBool: {
    name: "showFPSBool",
    availability: "now",
    type: "boolean",
    default: "FALSE",
  },
  showGazeBool: {
    name: "showGazeBool",
    availability: "now",
    type: "boolean",
    default: "FALSE",
  },
  showGazeNudgerBool: {
    name: "showGazeNudgerBool",
    availability: "now",
    type: "boolean",
    default: "FALSE",
  },
  showGrid: {
    name: "showGrid",
    availability: "now",
    type: "categorical",
    default: "disabled",
    categories: ["px", "cm", "deg", "mm", "none", "disabled"],
  },
  showPercentCorrectBool: {
    name: "showPercentCorrectBool",
    availability: "now",
    type: "boolean",
    default: "TRUE",
  },
  showProgressBarBool: {
    name: "showProgressBarBool",
    availability: "now",
    type: "boolean",
    default: "FALSE",
  },
  showTakeABreakCreditBool: {
    name: "showTakeABreakCreditBool",
    availability: "now",
    type: "boolean",
    default: "FALSE",
  },
  showTargetSpecsBool: {
    name: "showTargetSpecsBool",
    availability: "now",
    type: "boolean",
    default: "FALSE",
  },
  showText: {
    name: "showText",
    availability: "now",
    type: "text",
    default: "",
  },
  showViewingDistanceBool: {
    name: "showViewingDistanceBool",
    availability: "now",
    type: "boolean",
    default: "FALSE",
  },
  simulateParticipantBool: {
    name: "simulateParticipantBool",
    availability: "now",
    type: "boolean",
    default: "FALSE",
  },
  simulateWithDisplayBool: {
    name: "simulateWithDisplayBool",
    availability: "now",
    type: "boolean",
    default: "TRUE",
  },
  simulationBeta: {
    name: "simulationBeta",
    availability: "now",
    type: "numerical",
    default: "2.3",
  },
  simulationDelta: {
    name: "simulationDelta",
    availability: "now",
    type: "numerical",
    default: "0.01",
  },
  simulationModel: {
    name: "simulationModel",
    availability: "now",
    type: "categorical",
    default: "ideal",
    categories: ["right", "wrong", "blind", "weibull", "ideal"],
  },
  simulationThreshold: {
    name: "simulationThreshold",
    availability: "now",
    type: "numerical",
    default: "2",
  },
  soundGainDBSPL: {
    name: "soundGainDBSPL",
    availability: "now",
    type: "numerical",
    default: "125",
  },
  soundGainTWR: {
    name: "soundGainTWR",
    availability: "now",
    type: "text",
    default: "100,10,100",
  },
  spacingDeg: {
    name: "spacingDeg",
    availability: "now",
    type: "numerical",
    default: "2",
  },
  spacingDirection: {
    name: "spacingDirection",
    availability: "now",
    type: "categorical",
    default: "radial",
    categories: [
      "horizontal",
      "vertical",
      "horizontalAndVertical",
      "radial",
      "tangential",
      "radialAndTangential",
    ],
  },
  spacingIsOuterBool: {
    name: "spacingIsOuterBool",
    availability: "now",
    type: "boolean",
    default: "FALSE",
  },
  spacingOverSizeRatio: {
    name: "spacingOverSizeRatio",
    availability: "now",
    type: "numerical",
    default: "1.4",
  },
  spacingRelationToSize: {
    name: "spacingRelationToSize",
    availability: "now",
    type: "categorical",
    default: "ratio",
    categories: ["none", "ratio", "typographic"],
  },
  spacingSymmetry: {
    name: "spacingSymmetry",
    availability: "now",
    type: "categorical",
    default: "retina",
    categories: ["screen", "retina", "cortex"],
  },
  takeABreakMinimumDurationSec: {
    name: "takeABreakMinimumDurationSec",
    availability: "now",
    type: "numerical",
    default: "2",
  },
  takeABreakTrialCredit: {
    name: "takeABreakTrialCredit",
    availability: "now",
    type: "numerical",
    default: "0.05",
  },
  targetBoundingBoxHorizontalAlignment: {
    name: "targetBoundingBoxHorizontalAlignment",
    availability: "now",
    type: "categorical",
    default: "center",
    categories: ["center", "origin"],
  },
  targetContrast: {
    name: "targetContrast",
    availability: "now",
    type: "numerical",
    default: "-1",
  },
  targetCyclePerDeg: {
    name: "targetCyclePerDeg",
    availability: "now",
    type: "numerical",
    default: "0",
  },
  targetDelaySec: {
    name: "targetDelaySec",
    availability: "now",
    type: "numerical",
    default: "0",
  },
  targetDurationSec: {
    name: "targetDurationSec",
    availability: "now",
    type: "numerical",
    default: "0.15",
  },
  targetEccentricityXDeg: {
    name: "targetEccentricityXDeg",
    availability: "now",
    type: "numerical",
    default: "0",
  },
  targetEccentricityYDeg: {
    name: "targetEccentricityYDeg",
    availability: "now",
    type: "numerical",
    default: "0",
  },
  targetHz: {
    name: "targetHz",
    availability: "now",
    type: "numerical",
    default: "0",
  },
  targetImageFolder: {
    name: "targetImageFolder",
    availability: "now",
    type: "text",
    default: "",
  },
  targetKind: {
    name: "targetKind",
    availability: "now",
    type: "categorical",
    default: "letter",
    categories: [
      "letter",
      "gabor",
      "movie",
      "sound",
      "vocoderPhrase",
      "reading",
      "rsvpReading",
      "repeatedLetters",
    ],
  },
  targetMinimumPix: {
    name: "targetMinimumPix",
    availability: "now",
    type: "numerical",
    default: "8",
  },
  targetOrientationDeg: {
    name: "targetOrientationDeg",
    availability: "now",
    type: "numerical",
    default: "0",
  },
  targetPhaseSpatialDeg: {
    name: "targetPhaseSpatialDeg",
    availability: "now",
    type: "numerical",
    default: "0",
  },
  targetPhaseTemporalDeg: {
    name: "targetPhaseTemporalDeg",
    availability: "now",
    type: "numerical",
    default: "0",
  },
  targetRepeatsBorderCharacter: {
    name: "targetRepeatsBorderCharacter",
    availability: "now",
    type: "text",
    default: "$",
  },
  targetRepeatsMaxLines: {
    name: "targetRepeatsMaxLines",
    availability: "now",
    type: "numerical",
    default: "3",
  },
  targetSafetyMarginSec: {
    name: "targetSafetyMarginSec",
    availability: "now",
    type: "numerical",
    default: "0.7",
  },
  targetSizeDeg: {
    name: "targetSizeDeg",
    availability: "now",
    type: "numerical",
    default: "2",
  },
  targetSizeIsHeightBool: {
    name: "targetSizeIsHeightBool",
    availability: "now",
    type: "boolean",
    default: "FALSE",
  },
  targetSoundChannels: {
    name: "targetSoundChannels",
    availability: "now",
    type: "integer",
    default: "9",
  },
  targetSoundDBSPL: {
    name: "targetSoundDBSPL",
    availability: "now",
    type: "numerical",
    default: "20",
  },
  targetSoundFolder: {
    name: "targetSoundFolder",
    availability: "now",
    type: "text",
    default: "",
  },
  targetSoundNoiseBool: {
    name: "targetSoundNoiseBool",
    availability: "now",
    type: "boolean",
    default: "FALSE",
  },
  targetSoundNoiseClockHz: {
    name: "targetSoundNoiseClockHz",
    availability: "now",
    type: "numerical",
    default: "20000",
  },
  targetSoundNoiseDBSPL: {
    name: "targetSoundNoiseDBSPL",
    availability: "now",
    type: "numerical",
    default: "-999",
  },
  targetSoundNoiseOffsetReTargetSec: {
    name: "targetSoundNoiseOffsetReTargetSec",
    availability: "now",
    type: "numerical",
    default: "0.3",
  },
  targetSoundNoiseOnsetReTargetSec: {
    name: "targetSoundNoiseOnsetReTargetSec",
    availability: "now",
    type: "numerical",
    default: "-0.3",
  },
  targetSoundPhrase: {
    name: "targetSoundPhrase",
    availability: "now",
    type: "text",
    default: "",
  },
  targetSpaceConstantDeg: {
    name: "targetSpaceConstantDeg",
    availability: "now",
    type: "numerical",
    default: "1.00E+10",
  },
  targetTask: {
    name: "targetTask",
    availability: "now",
    type: "categorical",
    default: "UNDEFINED",
    categories: ["identify", "detect", "questionAndAnswer"],
  },
  targetTimeConstantSec: {
    name: "targetTimeConstantSec",
    availability: "now",
    type: "numerical",
    default: "1.00E+10",
  },
  targetWhenSec: {
    name: "targetWhenSec",
    availability: "now",
    type: "numerical",
    default: "0",
  },
  thresholdAllowedDurationRatio: {
    name: "thresholdAllowedDurationRatio",
    availability: "now",
    type: "numerical",
    default: "1.5",
  },
  thresholdAllowedGazeRErrorDeg: {
    name: "thresholdAllowedGazeRErrorDeg",
    availability: "now",
    type: "numerical",
    default: "1.00E+10",
  },
  thresholdAllowedGazeXErrorDeg: {
    name: "thresholdAllowedGazeXErrorDeg",
    availability: "now",
    type: "numerical",
    default: "1.00E+10",
  },
  thresholdAllowedGazeYErrorDeg: {
    name: "thresholdAllowedGazeYErrorDeg",
    availability: "now",
    type: "numerical",
    default: "1.00E+10",
  },
  thresholdAllowedLatenessSec: {
    name: "thresholdAllowedLatenessSec",
    availability: "now",
    type: "numerical",
    default: "0.1",
  },
  thresholdBeta: {
    name: "thresholdBeta",
    availability: "now",
    type: "numerical",
    default: "2.3",
  },
  thresholdDelta: {
    name: "thresholdDelta",
    availability: "now",
    type: "numerical",
    default: "0.01",
  },
  thresholdGamma: {
    name: "thresholdGamma",
    availability: "now",
    type: "numerical",
    default: "",
  },
  thresholdGuess: {
    name: "thresholdGuess",
    availability: "now",
    type: "numerical",
    default: "1",
  },
  thresholdGuessLogSd: {
    name: "thresholdGuessLogSd",
    availability: "now",
    type: "numerical",
    default: "2",
  },
  thresholdParameter: {
    name: "thresholdParameter",
    availability: "now",
    type: "categorical",
    default: "spacing",
    categories: [
      "spacing",
      "spacingDeg",
      "size",
      "targetSizeDeg",
      "targetDurationSec",
      "targetContrast",
      "soundLevel",
      "targetSoundDBSPL",
      "targetSoundNoiseDBSPL",
    ],
  },
  thresholdProcedure: {
    name: "thresholdProcedure",
    availability: "now",
    type: "categorical",
    default: "QUEST",
    categories: ["none", "QUEST"],
  },
  thresholdProportionCorrect: {
    name: "thresholdProportionCorrect",
    availability: "now",
    type: "numerical",
    default: "0.7",
  },
  thresholdRepeatBadBlockBool: {
    name: "thresholdRepeatBadBlockBool",
    availability: "now",
    type: "boolean",
    default: "FALSE",
  },
  viewingDistanceAllowedRatio: {
    name: "viewingDistanceAllowedRatio",
    availability: "now",
    type: "numerical",
    default: "1.2",
  },
  viewingDistanceDesiredCm: {
    name: "viewingDistanceDesiredCm",
    availability: "now",
    type: "numerical",
    default: "50",
  },
  viewingDistanceNudgingBool: {
    name: "viewingDistanceNudgingBool",
    availability: "now",
    type: "boolean",
    default: "FALSE",
  },
  closestPointEccentricitySetting: {
    name: "closestPointEccentricitySetting",
    availability: "now",
    type: "",
    default: "",
  },
};

export const SUPER_MATCHING_PARAMS: string[] = ["questionAndAnswer@@"];
