/* eslint-disable @typescript-eslint/no-explicit-any */
import { rmSync, readdirSync, existsSync } from "fs";
import { resolve } from "path";

const cleanupOldExamples = () => {
  // Help flag
  if (process.argv.includes("--help") || process.argv.includes("-h")) {
    console.log(`
Usage: ts-node cleanupOldExamples.ts [options]

Options:
  --dry-run, -n    Preview deletions without actually deleting
  --help, -h       Show this help message

Removes old generated example folders from examples/ root (now in examples/generated/).
Only deletes folders that:
  1. Correspond to a file in tables/ (i.e., are generated by this script)
  2. Contain both index.html and conditions/ (old generated structure)
  3. Are NOT in the skip‑list (input directories, generated/, etc.)
  4. Do NOT contain a .git subdirectory (git repos are preserved)
`);
    return;
  }

  const dryRun =
    process.argv.includes("--dry-run") || process.argv.includes("-n");
  if (dryRun) console.log("DRY RUN: No files will be deleted");

  // Compute dir same as buildExamples.ts
  let dir: string[] = [];
  try {
    const dirCount = readdirSync("tables/");
    dir = dirCount.filter((e) => e.match(/.*\.(xlsx|csv?)/gi));
  } catch (err) {
    console.warn(
      "Note: tables/ directory not found or inaccessible. No generated examples to clean up.",
    );
    return;
  }

  // Null guard + array safety
  const generatedExampleNames = dir?.map((f) => f.split(".")[0]) || [];

  const examplesRoot = __dirname;
  const skipList = [
    "fonts",
    "forms",
    "tables",
    "code",
    "texts",
    "folders",
    "images",
    "impulseResponses",
    "frequencyResponses",
    "targetSoundLists",
    "generated", // new output location
  ]; // google-fonts-variable-test omitted per your request

  try {
    const items = readdirSync(examplesRoot, { withFileTypes: true });
    items.forEach((dirent) => {
      if (!dirent.isDirectory()) return;
      const name = dirent.name;

      if (skipList.includes(name)) {
        console.log(`Skipping (skip‑list): ${name}`);
        return;
      }

      const folderPath = resolve(examplesRoot, name);

      // Git‑repo protection
      if (existsSync(resolve(folderPath, ".git"))) {
        console.log(`Skipping (git repo): ${name}`);
        return;
      }

      // Only remove if (1) name matches a generated example, AND
      // (2) has old generated structure (index.html + conditions/)
      if (generatedExampleNames.includes(name)) {
        const hasIndexHtml = existsSync(resolve(folderPath, "index.html"));
        const hasConditions = existsSync(resolve(folderPath, "conditions"));

        if (hasIndexHtml && hasConditions) {
          if (dryRun) {
            console.log(`[DRY RUN] Would delete: ${folderPath}`);
          } else {
            rmSync(folderPath, { recursive: true });
            console.log(`Deleted: ${folderPath}`);
          }
        } else {
          console.log(`Skipping (missing index.html or conditions/): ${name}`);
        }
      } else {
        console.log(`Skipping (not a generated example name): ${name}`);
      }
    });
  } catch (err) {
    console.warn("Note: Could not clean up some old examples (non‑critical)");
  }

  if (dryRun) console.log("Dry run complete. Use without --dry-run to delete.");
};

cleanupOldExamples();
